name: CI

on: 
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: | 
          cd app
          git reset --hard 
          git pull origin main 
          cp ../.env .env
          docker build --no-cache -t localhost:5000/app 
          docker push localhost:5000/app
          cd ../compose_app
          docker stack deploy -c docker-compose.yml app

    