name: CI

on: 
  push:
    branches:    
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --delete-before --force 
        path: /
        remote_path: /home/${{ secrets.USERNAME }}/app/
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSHKEY }}
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: | 
          cd app
          cp ../.env .env
          docker build --no-cache -t localhost:5000/cherrypy:latest .
          docker push localhost:5000/cherrypy:latest 
          cd ../compose_app
          docker stack deploy -c docker-compose.yml app

    